[program:php-tuic-client]
directory=/opt/php-tuic-client
command=/opt/php-tuic-client/scripts/start-tuic-client.sh
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/var/log/php-tuic-client.stdout.log
stderr_logfile=/var/log/php-tuic-client.stderr.log
environment=PHP_BIN="/usr/bin/php",TUIC_CONFIG="/opt/php-tuic-client/config/tuic.yaml",TUIC_HTTP_LISTEN="127.0.0.1:8080",TUIC_SOCKS_LISTEN="127.0.0.1:1080"
